# Generated by Django 3.0.3 on 2020-02-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('score', models.IntegerField(default=5, max_length=5)),
                ('body', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='New',
        ),
    ]
