# Generated by Django 3.0.3 on 2020-02-21 09:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evalapp', '0004_list_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='body',
            field=models.TextField(default='최대 5점. 5점을 초과하면 글이 안보입니다.'),
        ),
        migrations.AlterField(
            model_name='list',
            name='field',
            field=models.CharField(choices=[('이수영역 선택', '이수영역 선택'), ('전공', '전공'), ('교양', '교양'), ('선택', '선택')], default='이수영역 선택', max_length=10),
        ),
        migrations.AlterField(
            model_name='list',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=300)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='evalapp.List')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
