# Generated by Django 3.0.3 on 2020-02-21 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evalapp', '0005_auto_20200221_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contents',
            new_name='xcontents',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_comments', to='evalapp.List'),
        ),
    ]
