# Generated by Django 3.0.3 on 2020-02-21 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evalapp', '0006_auto_20200222_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='xcontents',
            new_name='contents',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='evalapp.List'),
        ),
    ]
