# Generated by Django 3.0.3 on 2020-02-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalapp', '0009_auto_20200222_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='body',
            field=models.TextField(),
        ),
    ]
